services:

  gateway:
    build: ./gateway
    ports:
      - "8080:8000"
    depends_on:
      - quiz-service
      - player-service
      - score-service

  quiz-service:
    build: ./services/quiz-service
    ports:
      - "8000:8000"
    depends_on:
      quiz-db:
        condition: service_healthy

  quiz-db:
    image: postgres:16
    container_name: quiz-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432"
    volumes:
      - quiz_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d quiz_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  player-service:
    build: ./services/player-service
    ports:
      - "8001:8001"
    depends_on:
      player-db:
        condition: service_healthy

  player-db:
    image: postgres:16
    container_name: player-db
    environment:
      POSTGRES_USER: player_user
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: player_db
    ports:
      - "5433:5432"
    volumes:
      - player_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U player_user -d player_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  score-service:
    build: ./services/score-service
    ports:
      - "8002:8002"
    depends_on:
      score-db:
        condition: service_healthy

  score-db:
    image: postgres:16
    container_name: score-db
    environment:
      POSTGRES_USER: score_user
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: score_db
    ports:
      - "5434:5432"
    volumes:
      - score_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U score_user -d score_db"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  quiz_data:
  player_data:
  score_data: